clone:
    hg:
        image: plugins/hg

pipeline:
    npm:
        image: node
        commands:
            - echo '{ "allow_root": true }' > ~/.bowerrc
            - npm -s install --unsafe-perm
            - npm test
        volumes:
            - cache-npm:/root/.npm
